---
settings:
    facebook:
        appId: APP_ID
        appSecret: APP_SECRET
connections:
    -
        name: con1
        host: localhost
        port: 3306
        user: user
        password: '123456'
        database: db-test-mysql
        provider: mysql
    -
        name: con2
        host: localhost
        port: 5432
        user: user
        password: '123456'
        database: db-test-pg
        provider: pg
